spring:
  application:
    name: pokemonservice
  datasource:
    port: 3306
    url: jdbc:mysql://localhost:3306/ProjectPokemonPokemon
    database: ProjectPokemonPokemon
    username: root
    password: root
    ssl: false
